[package]
name = "ppp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbkdf2 = "0.12.2"
sha2 = "0.10.7"
tiny-bip39 = "1.0.0"
